#!/usr/bin/env bash
# Configuring a server with specification XYZ
if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
#elif [ "$#" -lt 2 ]; then
	#scp "$1" "$3@$2"!:~/
else
	scp -i StrictHostKeyChecking=no "$4" "$1" "$3@$2":~/
fi
