#!/usr/bin/env bash
#an update
sudo apt-get -y update

#install Nginx
sudo apt-get -y install nginx
#a nginx configuration
sudo service nginx start
sudo sh -c 'echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html;
		server_name_;
        location / {
            return 200 \"Hello World!\n\";
		}
}" > /etc/nginx/sites-available/default'

# Restart Nginx to apply the changes
sudo service nginx restart
