#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Create a server block configuration with the custom 404 page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
