#!/usr/bin/env bash
#bash script that loops from 1 to 10 and:
count=1
while [ $count -le 20 ]
do
  case $count in
    4)
      echo "$count"
	  echo "bad luck from China"
      ;;
    9)
      echo "$count"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$count"
      echo "and then bad luck from Italy"
      ;;
    *)
      echo "$count"
      ;;
    esac
      count=$((count+1))
done
