#!/usr/bin/env bash
#bash script that loops from 1 to 10 and:

hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo $minute
		minute=$((minute+1))
	done
	if [ $hour -eq 1 ]; then
        echo "9"
    fi
	hour=$((hour+1))
done
