#!/usr/bin/env bash
#bash script that loops from 1 to 10 and:

hr=0
while [ $hr -le 12 ]
do
	echo "$Hour: $hr"
	minute=1
	while [ $minute -le 59 ]
	do
	  echo $minute
	  minute=$((minute+1))
	done
	hr=$((hr+1))
done
