#!/usr/bin/env bash
#a Bash script that displays:The content of the current directory
for file in *;
do
  # Check if the file is not a directory and is not hidden
  if [[ -f "$file" && "$file" != .* ]];
  then
    # Use cut to extract the part of the name after the first dash
    name_part=$(echo "$file" | cut -d'-' -f2-)
    echo "$name_part"
  fi
done
