#!/usr/bin/env bash
#an update
sudo apt-get -y update

#install Nginx
sudo apt-get -y install nginx

# custom header and value
custom_header_name="X-served-By"
custom_header_value="$(hostname)"

#a nginx configuration as per custom header
config_file="/etc/nginx/sites-available/default"
sudo sed -i "/server_name _;/a \\\tadd_header $custom_header_name $custom_header_value;" "$config_file"

# Reload Nginx to apply the changes
sudo service nginx reload
