#!/usr/bin/env bash
#a Bash script that displays all active
#IPv4 IPs on the machine it’s executed on.

ip_addresses=$(ip -4 addr show | grep "inet " | awk '{print $2}' | cut -d'/' -f1)
# Loop through the different IP addresses and display them
for address in $ip_addresses;
do
  echo "$address"
done
