#!/usr/bin/env bash
private_key="school"
bits=4096
ssh-keygen -t rsa -b $bits -f "$private_key" -N "betty"
echo "RSA key pair created successfully. Private key: $private_key, Bits: $bits, Passphrase: betty"
